# === MongoDB Configuration ===
MONGO_HOST = "localhost"
MONGO_PORT = "27017"
MONGO_USERNAME = "admin"
MONGO_PASSWORD = "password123"
MONGO_AUTH_SOURCE = "admin"
MONGO_DB = "quant"
MONGO_COLLECTION = "backtest_records"
MONGO_MARKET_COLLECTION = "market_bars"
MONGO_MIGRATE_FROM_SQLITE = True
MONGO_USE_FALLBACK = False
MONGO_TIMEOUT_MS = 2000

DATA_SYNC_CRON_HOUR = 15
DATA_SYNC_CRON_MINUTE = 10
DATA_SYNC_ASSET_TYPES = ["stock", "fund", "futures"]
DATA_SYNC_STOCK_SYMBOLS = []
DATA_SYNC_FUND_SYMBOLS = []
DATA_SYNC_FUTURES_SYMBOLS = []
DATA_SYNC_STOCK_LIMIT = 0
DATA_SYNC_FUND_LIMIT = 0
DATA_SYNC_FUTURES_LIMIT = 0

# === Proxy Configuration ===
# Explicitly disable proxies to prevent connection issues
DISABLE_PROXIES = True
